version: '3'
services:
  red-app:
    build: ./red
    container_name: red-app
    networks:
      traffic-light:
        ipv4_address: 172.31.0.2

  yellow-app:
    build: ./yellow
    container_name: yellow-app
    networks:
      traffic-light:
        ipv4_address: 172.31.0.3

  green-app:
    build: ./green
    container_name: green-app
    networks:
      traffic-light:
        ipv4_address: 172.31.0.4

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.htpasswd:/etc/nginx/conf.d/.htpasswd:ro
    ports:
      - "3000:3000"
      - "4000:4000"
      - "5000:5000"
    depends_on:
      - red-app
      - yellow-app
      - green-app
    networks:
      traffic-light:
        ipv4_address: 172.31.0.5

networks:
  traffic-light:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
