version: '3'
services:
  red-app:
    build: ../proxyInverso/red
    container_name: balanceador_red-app
    networks:
      - traffic-light

  yellow-app:
    build: ../proxyInverso/yellow
    container_name: balanceador_yellow-app
    networks:
      - traffic-light

  green-app:
    build: ../proxyInverso/green
    container_name: balanceador_green-app
    networks:
      - traffic-light

  nginx:
    image: nginx:latest
    container_name: balanceador_nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.htpasswd:/etc/nginx/conf.d/.htpasswd:ro
    ports:
      - "3000:3000"
    depends_on:
      - red-app
      - yellow-app
      - green-app
    networks:
      - traffic-light

networks:
  traffic-light:
    driver: bridge
